# Generated by Django 4.2 on 2023-04-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=150)),
                ('module_name', models.CharField(blank=True, max_length=150)),
                ('model_name', models.CharField(blank=True, max_length=150)),
                ('permission', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
